// filepath: /Users/mouadsmac/aji-tfarraj-mobile/flutter_app/lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// API keys are loaded from environment variables using --dart-define.
///
/// To run the app:
/// ```bash
/// flutter run \
///   --dart-define=FIREBASE_ANDROID_API_KEY=your_android_key \
///   --dart-define=FIREBASE_IOS_API_KEY=your_ios_key
/// ```
///
/// Or create a `.env` file and use a package like flutter_dotenv.
class DefaultFirebaseOptions {
  // Environment variables for API keys
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: '',
  );

  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
    defaultValue: '',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase Android configuration
  // Package: com.ajitfarraj.aji_tfarraj
  static FirebaseOptions get android {
    assert(_androidApiKey.isNotEmpty,
        'FIREBASE_ANDROID_API_KEY not set. Run with --dart-define=FIREBASE_ANDROID_API_KEY=your_key');
    return FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:600996591716:android:c408a5cfb10172a6728771',
      messagingSenderId: '600996591716',
      projectId: 'aji-tfarraj',
      storageBucket: 'aji-tfarraj.firebasestorage.app',
    );
  }

  // Firebase iOS configuration
  // Bundle ID: com.ajitfarraj.ajiTfarraj
  static FirebaseOptions get ios {
    assert(_iosApiKey.isNotEmpty,
        'FIREBASE_IOS_API_KEY not set. Run with --dart-define=FIREBASE_IOS_API_KEY=your_key');
    return FirebaseOptions(
      apiKey: _iosApiKey,
      appId: '1:600996591716:ios:27e2a179987a6331728771',
      messagingSenderId: '600996591716',
      projectId: 'aji-tfarraj',
      storageBucket: 'aji-tfarraj.firebasestorage.app',
      iosBundleId: 'com.ajitfarraj.ajiTfarraj',
    );
  }
}
