// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Package: com.ajitfarraj.aji_tfarraj
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuYhmJhfJFbH2etFL60WCN_2bSK2OsRvo',
    appId: '1:600996591716:android:c408a5cfb10172a6728771',
    messagingSenderId: '600996591716',
    projectId: 'aji-tfarraj',
    storageBucket: 'aji-tfarraj.firebasestorage.app',
  );

  // Bundle ID: com.ajitfarraj.ajiTfarraj
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRbKSIKFb5qWrdUer3MznKsaK21efIueg',
    appId: '1:600996591716:ios:27e2a179987a6331728771',
    messagingSenderId: '600996591716',
    projectId: 'aji-tfarraj',
    storageBucket: 'aji-tfarraj.firebasestorage.app',
    iosBundleId: 'com.ajitfarraj.ajiTfarraj',
  );
}
